### ISSUE TITLE
Compression levels?

### ISSUE THREAD

**Issue by nickchomey** [rustic-rs/rustic#106]
What are the compression levels? There isn't any guidance in the help display

```
--set-compression <LEVEL>
            set compression level, 0 equals no compression
```

And which type of compression is used? zstd?

**Comment by aawsome** [comment]
Thanks for the question! Its zstd and allows currently between 0 (no compression) and 22. If not set (and repo version is 2 which is standard), the zstd standard compression level is used, which is 5 IIRC.

I think this should be added in the command or the docu to close your issue.

**Comment by aawsome** [comment]
Thanks for the question! Actually I didn't dive into zstd and just read somewhere that only the positve levels should be exposed to users.

But yes, negative values also work, in fact AFAIK rust uses the facebook zstd implementation, so all options that are allowed by the standard also work within rustic. I only changed the value "0" (usually set to default compression) into disabling compression at all.

**Comment by aawsome** [comment]
Ah, and to set negative compressions, you have to use `rustic-rs config --set-compression=-4` instead of `rustic-rs config --set-compression -4` (the latter bails that the option `-4` is not supported).

**Comment by aawsome** [comment]
Actually this result is not completely unexpected: The time added by higher compression is probably more than saved due to the lower size to save in the backend.

In fact, the "best" compression level to get a fast backup depends a lot on the CPU you are using AND the possible write speed of your backend (which again may depend on your upload bandwidth if you are  using a remote backend).

I agree, we should leave this issue open until the docu is more precise.
