### ISSUE TITLE
`The system cannot find the path specified` is not providing info about the problematic path

### ISSUE THREAD

**Issue by AlphaJack** [rustic-rs/rustic#1105]
Hi, I'm trying to launch rustic on windows, but I receive the error below:

```
rustic --log-level debug --use-profile "D:/Configurations/Test" show-config
error: rustic-rs fatal error: I/O operation failed: The system cannot find the path specified. (os error 3)
```

Is it possible to have the problematic path printed, at least with `debug` on, as it could be either the source or the destination?

I know it does not refer to the profile path, otherwise it would complain with:

```
rustic --log-level debug --use-profile "D:/Configurations/non-existent" show-config
[WARN] using no config file, none of these exist: D:/Configurations/non-existent.toml, D:/Configurations/rusticfds.toml, D:/Configurations/non-existent.toml
```

A minor issue is that it prints the same path 3 times if an absolute profile path is given

**Comment by AlphaJack** [comment]
Apparently it referred to the log location, as the parent folder does not exist.

Is it a wanted behavior or should rustic create missing parent folders?

**Comment by aawsome** [comment]
@AlphaJack Thanks a lot for reporting!
I just made a PR to fix it.

**Comment by Nahor** [comment]
Is this really a good idea?
- If the path is missing, I think it's more likely because of a typo rather than no directory ("/car/log"). It would only create a mess if "random" directories start popping-up on someone's drive. 
- There is good chance that the directory can't be created either (e.g. "/car/log" requires root access).

It would be better to improve the error message instead and let the use decide how to proceed (fix the typo, create the directory, choose a different location, ...).
