### ISSUE TITLE
Customize progress bars update

### ISSUE THREAD

**Issue by borkd** [rustic-rs/rustic#276]
Option to show progress info with given frequency as a line of text without control characters would be super useful. See restic's RESTIC_PROGRESS_FPS for the behavior I have in mind.

Option to force progress bars off altogether would work as an alternative when rustic is to be executed unattended under logged screen sessions.  As of now session logfiles which take ~20 KiB each with restic use hundreds of megabytes each with rustic.

**Comment by aawsome** [comment]
As far as I know, the progress bars do not show at all when you are using a non-interactive terminal. I use a systemd service to run my backups and don't get progress bars in the logs.
Can you describe your environment in more detail where you get the non-expected progress bars?

**Comment by borkd** [comment]
Logged (screen) sessions with full terminal emulation

**Comment by aawsome** [comment]
Mhh - if you use a standard terminal, the progress bars are shown... 
I hesitate a bit to add an option to rustic. In my opinion the standards defined by the indicatif crate should be ok, as this is exactly designed to provide progress bars and handle all kinds of edge cases...

Note that the progress bars are printed to stderr, so you can try to use `rustic ... 2>/dev/null` to get rid of the progress bars.
This will also omit the logging output, but this you could also redirect to a file using `--log-file`.

Actually, I don't really see why you are using your logged screen sessions setup. Which benefit do you see to use this instead of an automated run? Or the other way round: which problem are you solving by using this setup?

**Comment by aawsome** [comment]
About the metrics: Do you know that rustic stores a lot of metrics already in the snapshot?
You can access them by using `rustic snapshot <ID> --long` or `rustic snapshot <ID> --json`.
You can also get the metrics for all snapshots if you omit the `<ID>` in the above command. Also `<ID>` = `latest` is supported. Are there other metrics than the saved ones which you are missing?

**Comment by borkd** [comment]
Yes. Extra metadata stashed by rustic is handy, but does not cover everything I care about.

Switching between production/restic and testing/rustic also means I need to capture everythig I care about from restic runs too

**Comment by aawsome** [comment]
#279 adds the possibility to specify an interval for updating the progress bar. Note that you must specify a duration, e.g. `1s`, `1m`, `10ms` instead of a FPS.
The default interval is still 100ms.

@borkd Can you test if #279 suits your needs?

**Comment by borkd** [comment]
> @borkd Can you test if #279 suits your needs?
 
Will do, thank you
