### ISSUE TITLE
rustic is making multiple snapshots when given multiple sources

### ISSUE THREAD

**Issue by schmud** [rustic-rs/rustic#289]
When executing rustic like this:
```
% rustic backup tmp/rustic tmp/Cover.jpg
```
rustic creates 2 seperate snapshots. Is this intended behaviour? 
restic is handling multiple sources on command line differently.

(Edit: fixed typo)

**Comment by aawsome** [comment]
This is intended behavior. Actually for me this is a feature as I used to want different snapshots for different paths. Rustic can do this in one run with just once the startup overhead (like reading the index).

If you want to have just 1 snapshot, you have the following options:
- specify the files you want to include/exclude as globs, see the various *glob* options
- wait for #43 which will allow to merge snapshots. I think when this is tackled there will be also a `--merge` option for the backup commands which will automatically merge all snapshots into one (so yielding exactly the behavior of restic)

**Comment by aawsome** [comment]
Because it is not fully straightforward, here is an example how to use globs in your use-case:
- You basically want to backup `tmp`
- but exclude everything except included files, this can be achieved e.g. by `-g '!*'`
- then explicitly include the wanted files, i.e. `-g rustic -g Cover.jpg`

So your backup command could look like:
```
rustic backup -g '!*' -g rustic -g Cover.jpg tmp/
```

Note that using globs with subdirs is a bit tricky: If you exclude some dir, it is not even traversed. So an include glob would not apply within a subdir if the subdir itself is excluded by another glob. But basically globs syntax and functionality is exactly like `.gitignore` files with the `!`s inverted.
