### ISSUE TITLE
rustic.toml: dry-run not respected, but silently ignored

### ISSUE THREAD

**Issue by dimejo** [rustic-rs/rustic#459]
My `rustic.toml` has this part in it:
```
[...]

[forget]
dry-run = true
keep-hourly = 24
keep-daily = 30
keep-weekly = 52
keep-monthly = 60

[backup]

[...]
```
I ran `rustic forget` on the command line and expected it to use the --dry-run flag, but it didn't. Snapshots were removed. Is this flag not supported in a config file, or did I use it incorrectly?

**Comment by aawsome** [comment]
The dry-run flag is actually not supported. I found it a bit counter-intuitive to put `dry-run` into a config file which I would suppose is a configuration for the every-day use. I'd rather put the forget retention options into the config file and run `rustic forget -n` - that's why it's not supported currently. But it can be added of course.

A problem is  that there is no error if you specify some wrong or unsupported options in the config file. I'll think about how to add this...

**Comment by dimejo** [comment]
> The dry-run flag is actually not supported. I found it a bit counter-intuitive to put dry-run into a config file which I would suppose is a configuration for the every-day use. I'd rather put the forget retention options into the config file and run rustic forget -n - that's why it's not supported currently. But it can be added of course.

I don't know if it would make sense for someone. I wanted to test some settings for cronjobs and expected all command line flags to be supported by the configuration file.

> A problem is that there is no error if you specify some wrong or unsupported options in the config file. I'll think about how to add this...

Printing a warning for unsupported options (or typos!) would definitely be a plus!

**Comment by aawsome** [comment]
I would like to keep the dry run behavior for now as it is, as I'm just thinking about putting it into the general options in the future and that would make a configuration file migration necessary - so I'd like to better prevent this.

But I've just added #462 which should fix the problem that you don't get feedback if a field in the TOML is not supported.

**Comment by dimejo** [comment]
Awesome, thanks for the fast fix!
