### ISSUE TITLE
modifying config with `rustic config` makes the repo unusable by restic

### ISSUE THREAD

**Issue by jck** [rustic-rs/rustic#499]
After setting the compression level of a repo using `rustic config --set-compression 22`, I can no longer use that repo with restic.

```
$ restic stats
Fatal: config cannot be loaded: invalid character '\x02' looking for beginning of value
```

```
restic 0.15.1 
rustic v0.4.4
```

**Comment by aawsome** [comment]
Should be fixed by #500.
Rustic is still able to read a compressed config file. So, to fix an existing compressed config file, you have to use a new version including #500 (currently: available in the beta builds) and run a `rusitic config` which does really change the config. E.g. disable compression and then re-enable it.
