### ISSUE TITLE
Extended attributes support

### ISSUE THREAD

**Issue by jvandenbroek** [rustic-rs/rustic#514]
Would be great if you could add extended attributes support for both backup and restore. Currently I'm forced to use restic mainly because of this, which is unfortunate, since rustic seems to be more optimized. Also really like the restore --delete feature, makes life much easier ;-)

**Comment by aawsome** [comment]
I'll try to work on it! Actually I didn't need this feature so for, so it wasn't on my prio list.
But as it is a restic compatibility issue, it is within the goals of rustic to also have it.

**Comment by aawsome** [comment]
Thanks for testing. Mhh.. dirs should also work. Can you run with `--log-level=debug` to see if metadata are also being changed for your dir?
Additionally, you could run `restic backup` and `rustic backup` and show the corresponding trees. This can be easily done by using `rustic cat tree <snapid>:path`

**Comment by jvandenbroek** [comment]
I'm sorry, you're absolutely right! Subdirs do include the attributes, the root dir (the one specified to restore) itself doesn't. If that's an easy fix, great, otherwise I'm happy with the current implementation.

**Comment by aawsome** [comment]
The metadata for the "restore root dir" is not restored. 

The reason is that the metadata for root snapshot dir is not saved (also not when backing up with restic) - that means if you run `restore <SNAP> /target/`, the metadata of `/target/` cannot be set.

For subdirs it would be possible in principle, but is not implemented as the implementation is done for the general case only...

So I'll merge #522 now and leave this "root dir metadata" topic open. Feel free to open an issue for that!
