### ISSUE TITLE
Support for exclude/include with `restore`

### ISSUE THREAD

**Issue by parasiteoflife** [rustic-rs/rustic#518]
Please, add support for --exclude and --include flags for the restoring operation so we can have more control on what or what not to restore.

https://github.com/rustic-rs/rustic/discussions/516

**Comment by jvandenbroek** [comment]
Normally I just +1 requests, but I want to emphasize the importance of this for me and probably others as well. I was restoring a pretty big repo today with restic (bc i needed the exclude filter) and ran out of space on the specific target. After fixing that I wanted to resume it, only to figure out it was downloading everything again, not skipping what already was restored.. Not what I expected. With include / exclude filters (in this case exclude) I could have just used rustic for this.

**Comment by aawsome** [comment]
#572 adds several glob options which should work like the corresponding options in the `backup` command.
Can you test if these work for you?

**Comment by aawsome** [comment]
I updated #572. Now you can also test the glob options using the `ls` command.

**Comment by jvandenbroek** [comment]
aawsome! ;-)
Quick test only restoring /etc, works well (took me a while to get the correct syntax):
`rustic restore latest --glob \!\*\* --glob /etc --glob /etc/\*\* /target`

Probably not related, but I notice it gives warnings on all symlinks and indeed doesn't set correct times:
```
[WARN] restore "etc/systemd/system/syslog.service": setting User/Group failed.
[WARN] restore "etc/systemd/system/syslog.service": chmod failed.
[WARN] restore "etc/systemd/system/syslog.service": setting file times failed.
```

**Comment by aawsome** [comment]
@jvandenbroek Thanks for testing! Actually using `--glob /etc --glob '/etc/**' should also work. If you omit the first one, the `/etc` dir will still be created but metadata will not be restored for it.

Can you open a separate issue for the symlink medata topic?

**Comment by aawsome** [comment]
@parasiteoflife To only exclude a specific path, use the `--glob !path` syntax. If the glob only contains blacklist patterns, all non-matched content is included.

**Comment by aawsome** [comment]
@parasiteoflife Thanks for reporting. I'm quite sure that this is not related with the `--glob` options. The `restore` command simply a the list (technically: an iterator) of files and processes them. The `--glob` options are taken into account when generating this list. To check if `--glob` works, you can also run a `rustic ls` command with the glob which simply shows the list instead of processing it.

About your `restore` command: In fact, it looks like rustic didn't find a single existing file. Are you sure that the restore did work?

**Comment by aawsome** [comment]
Seems your first restore got aborted due to some error in the REST backend. Maybe that was the problem..?!?
Did you try another `restore` run (you can also use `--dry-run`)  after your second run?

Also you could try to print out the diff of the snapshot and your restored dir using `rustic diff` (also supports the `--glob` options)
