### ISSUE TITLE
Backup of dirs with spaces still not working

### ISSUE THREAD

**Issue by waspoza** [rustic-rs/rustic#583]
```
$ ./rustic -V
rustic v0.5.1

$ ./rustic -P test backup
using config ./test.toml
[INFO] repository local:/home/piotr/rustic_test: password is correct.
[INFO] using cache at /home/piotr/.cache/rustic/bcbb400559f5e2d884f009f8f2be955e401245d14ac73bc8607b7bc0db3d4e79
[WARN] error sanitizing source="/home/piotr/dir with spaces" in config file: No such file or directory (os error 2)
[INFO] using all backup sources from config file.

$ ls /home/piotr/dir\ with\ spaces/
drwxr-xr-x  1 piotr piotr    4 2023-03-31 19:10 .
drwx--x---+ 1 piotr piotr 1.1K 2023-04-14 11:16 ..
-rw-r--r--  1 piotr piotr    0 2023-03-31 19:10 aa
```

**Comment by aawsome** [comment]
Can you show how you defined the source in your config file?

**Comment by waspoza** [comment]
```
[[backup.sources]]
source = "/home/piotr/dir with spaces"
```

**Comment by aawsome** [comment]
If you specify the source in this way, rustic wants to backup 3 directories: `"/home/piotr/dir", "with", "spaces"`. As multiple dirs are allowed as source and those dirs are separated by a space, dirs with spaces needs to be wrapped, e.g.:
```
[[backup.sources]]
source = "'/home/piotr/dir with spaces'"
```
or 
```
[[backup.sources]]
source = '"/home/piotr/dir with spaces"'
```
(note the order of `'` and `"` is swapped)

**Comment by waspoza** [comment]
Oh i see. Yes now it's working, thanks!

On unrelated note, not sure if its only me, but i'm getting repetition of messages even when rustic is run directly from the terminal:
![Screenshot from 2023-04-14 11-33-29](https://user-images.githubusercontent.com/4631033/232008074-959a81c8-10ed-4fff-a1d4-18b13807302c.png)

**Comment by aawsome** [comment]
Thanks for the feedback.

About the progress messages: The progress bars by default update 10 times per second. It seems that in your case each update gives a new line. Maybe this is because of a speciality in your terminal, maybe your terminal width is too small to cover the full line (including the `\n`).
If the width is a problem, try with a wider terminal. In any case there are the options `--no-progress` and `--progress-interval` available to modify progress bar behavior.

I'm closing this "dirs with spaces issue" as resolved.

**Comment by waspoza** [comment]
Sure thing. Thanks again!
