### ISSUE TITLE
Check crashes

### ISSUE THREAD

**Issue by borkd** [rustic-rs/rustic#638]
Hi,

Repo check using latest release crashes on one particular repo. Older version completes. Restic check shows no errors. 

1321 snapshots, 2.1TiB repo

```
[INFO] using no cache
thread "<unnamed>" panicked at "called Result: :unwrap() on an 'Err' value: "SendError(..)"', src/blob/tree.rs:265:26
stack backtrace:
Error: invalid type: null, expected a base64 encoded string at line 1 column 6999
Command exited with non-zero status 1

```

**Comment by aawsome** [comment]
Thanks for reporting. The error handling is not perfect here, unfortunately.
But I think the root cause is that you have extended file Attributes which seem to have a name but no value and are saved (by restic, I assume) as `{"name": "<NAME">, "value": null}`. rustic can currently not read this and displays an error.

Can you 
- Give the last rustic version where the check succeeded and the first where it fails?
- Confirm that the repo or at least some snapshots were generated by restic?

**Comment by aawsome** [comment]
You can also try if #640 fixes the problem - there I solved the potential xattr issue.
