### ISSUE TITLE
Add possibility to init repos to copy to with suitable chunker parameters // was: Cannot copy to repo with different chunker

### ISSUE THREAD

**Issue by Deedasmi** [rustic-rs/rustic#639]
I'm trying to have a local copy and a remote copy. My understanding is the way to do this is to have two repositories and copy one to the other.

Configuration

local:
```
[repository]
repository = "/home/deedasmi/backups/rustic"
password....
no-cache = true

[backup]
git-ignore = true

[[backup.sources]]
source = "/home/deedasmi/.config"

....more sources...

[[copy.targets]]
repository = "rclone:REDACTED:rustic"
password....
cache-dir = "/tmp/rustic"
```

remote:
```
[repository]
repository = "rclone:REDACTED:rustic"
password.....
cache-dir = "/tmp/rustic"
```

I was able to initialize the repository, but when I try to copy snapshots I get 

> Error: cannot copy to repository with different chunker parameter (re-chunking not implemented)!

In theory, shouldn't these repos have the same chunking parameters (default)? Am I missing something on how to configure these to match?

**Comment by aawsome** [comment]
Thanks for reporting! Actually this check is added to prevent irritations if you copy snapshots from one repository to another one which already contains snapshots/data. 
If in this case the chunker parameters do not match, you don't get deduplication which may irritate people.

About the chunker parameter: In fact, they are different by default as a random Polynomial is chosen. This is to prevent fingerprinting-like attacks. If a default parameter would be chosen for every repository, an enemy could (in theory) gain knowledge if a specific data was added to the repository by only looking at changes on the repository files, but without the need to break the crypto.

So, the solution to your problem is to initialize the remote repo with the identical junker parameters as your local repo. Unfortunately, this isn't current possible in rustic. I will add a `--init` option to the copy command which does exactly this.

As workaround you can manually initialize your remote repository with r**e**stic, using `restic init --from-repo` and then use it with `rustic copy`.

**Comment by Deedasmi** [comment]
Ah, I've not use restic, straight here. But the explanation makes sense. Thanks!

**Comment by aawsome** [comment]
I just created #643 in case you want to use rustic to initialize the target repositories
